import fs from "fs";
import path from "path";

/**
 * File content cache with TTL support
 */
interface CacheEntry {
  content: string;
  timestamp: number;
}

const fileCache = new Map<string, CacheEntry>();
const CACHE_TTL = 1000 * 60 * 5; // 5 minutes
const MAX_CACHE_SIZE = 100;

/**
 * Pre-compiled regex patterns for better performance
 */
const EXPORT_PATTERNS = {
  defaultExport: /export\s+default\s+(\{[\s\S]*\});?\s*$/,
  namedExport: /export\s+const\s+\w+\s*=\s*(\{[\s\S]*\});?\s*$/,
};

/**
 * Get file content with caching
 */
function getFileContent(filePath: string): string | null {
  const resolvedPath = path.resolve(filePath);

  // Check cache first
  const cacheEntry = fileCache.get(resolvedPath);
  if (cacheEntry) {
    // Check if cache entry is still valid
    const now = Date.now();
    if (now - cacheEntry.timestamp < CACHE_TTL) {
      return cacheEntry.content;
    }
    // Cache expired, remove it
    fileCache.delete(resolvedPath);
  }

  // Validate file path is within project directory
  if (!resolvedPath.startsWith(process.cwd())) {
    throw new Error(`Security: File path outside project directory: ${filePath}`);
  }

  if (!fs.existsSync(resolvedPath)) {
    return null;
  }

  // Read file content
  const content = fs.readFileSync(resolvedPath, "utf-8");

  // Add to cache (evict oldest if cache is full)
  if (fileCache.size >= MAX_CACHE_SIZE) {
    let oldestKey: string | null = null;
    let oldestTime = Infinity;

    for (const [key, entry] of fileCache) {
      if (entry.timestamp < oldestTime) {
        oldestTime = entry.timestamp;
        oldestKey = key;
      }
    }

    if (oldestKey) {
      fileCache.delete(oldestKey);
    }
  }

  fileCache.set(resolvedPath, {
    content,
    timestamp: Date.now(),
  });

  return content;
}

/**
 * Parses a TypeScript file containing an object export
 * @description Improved parser with caching and better error handling
 * @security Note: Uses Function constructor - only use with trusted local files
 */
export function parseTypeScriptFile(filePath: string): Record<string, unknown> {
  const content = getFileContent(filePath);
  if (!content) return {};

  // Try to match export patterns (pre-compiled for performance)
  let match: RegExpExecArray | null = null;
  let objStr = "";

  // Try default export first
  match = EXPORT_PATTERNS.defaultExport.exec(content);
  if (match && match[1]) {
    objStr = match[1];
  } else {
    // Try named export
    match = EXPORT_PATTERNS.namedExport.exec(content);
    if (match && match[1]) {
      objStr = match[1];
    }
  }

  if (!objStr) {
    return {};
  }

  try {
    // Evaluate the object string to a real JS object
    // Using Function instead of eval for slightly better safety
    const obj = new Function(`"use strict"; return (${objStr})`)();
    return obj;
  } catch (err) {
    console.error(`Error parsing ${filePath}:`, err);
    return {};
  }
}

/**
 * Generates a TypeScript file content from an object
 * @description Optimized content generation with proper escaping
 */
export function generateTypeScriptContent(obj: Record<string, unknown>, langCode?: string): string {
  // Use JSON.stringify with proper indentation
  const jsonStr = JSON.stringify(obj, null, 2);

  return `/**
 * Localization: ${langCode || "unknown"}
 * Generated by @umituz/web-localization
 */

export default ${jsonStr};
`;
}

/**
 * Clear file content cache
 * @description Call this when you know files have been modified externally
 */
export function clearFileCache(): void {
  fileCache.clear();
}

/**
 * Get cache statistics
 */
export function getFileCacheStats(): { size: number; maxSize: number } {
  return {
    size: fileCache.size,
    maxSize: MAX_CACHE_SIZE,
  };
}

/**
 * Check if a file exists (async version for better performance)
 */
export async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.promises.access(filePath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Read file content asynchronously (for better performance in non-blocking scenarios)
 */
export async function readFileAsync(filePath: string): Promise<string | null> {
  const resolvedPath = path.resolve(filePath);

  // Validate file path is within project directory
  if (!resolvedPath.startsWith(process.cwd())) {
    throw new Error(`Security: File path outside project directory: ${filePath}`);
  }

  try {
    const content = await fs.promises.readFile(resolvedPath, "utf-8");

    // Update cache
    fileCache.set(resolvedPath, {
      content,
      timestamp: Date.now(),
    });

    return content;
  } catch (err) {
    return null;
  }
}

/**
 * Write file content asynchronously (for better performance in non-blocking scenarios)
 */
export async function writeFileAsync(filePath: string, content: string): Promise<void> {
  const resolvedPath = path.resolve(filePath);

  // Validate file path is within project directory
  if (!resolvedPath.startsWith(process.cwd())) {
    throw new Error(`Security: File path outside project directory: ${filePath}`);
  }

  // Ensure directory exists
  const dir = path.dirname(resolvedPath);
  await fs.promises.mkdir(dir, { recursive: true });

  // Write file
  await fs.promises.writeFile(resolvedPath, content, "utf-8");

  // Update cache
  fileCache.set(resolvedPath, {
    content,
    timestamp: Date.now(),
  });
}
