import fs from "fs";

/**
 * Parses a TypeScript file containing an object export
 * @description Simplistic parser for 'export default { ... }' or 'export const data = { ... }'
 */
export function parseTypeScriptFile(filePath: string): Record<string, unknown> {
  if (!fs.existsSync(filePath)) return {};
  
  const content = fs.readFileSync(filePath, "utf-8");
  
  // Extract the object part
  // This is a naive implementation, but matches the pattern used in the project
  const match = content.match(/export (default|const [^=]+ =) (\{[\s\S]*\});?\s*$/);
  if (!match) return {};
  
  try {
    // Evaluate the object string to a real JS object
    // Using Function instead of eval for slightly better safety
    const objStr = match[2];
    const obj = new Function(`return ${objStr}`)();
    return obj;
  } catch (err) {
    console.error(`Error parsing ${filePath}:`, err);
    return {};
  }
}

/**
 * Generates a TypeScript file content from an object
 */
export function generateTypeScriptContent(obj: Record<string, unknown>, langCode?: string): string {
  const jsonStr = JSON.stringify(obj, null, 2);
  
  // Clean up keys (remove quotes if possible, though JSON.stringify adds them)
  // For simplicity, we'll keep them as valid JS objects
  
  return `/**
 * Localization: ${langCode || "unknown"}
 * Generated by @umituz/web-localization
 */

export default ${jsonStr};
`;
}
